import assert from 'node:assert/strict';
const origin=process.argv[2]||'http://localhost:5173';
const nonce=Date.now();
function client(){let cookie='';return {async call(body,status=200){const r=await fetch(origin+'/api/gather',{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json',Origin:origin}:{}),...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d;}};}
const owner=client(),guest=client(),staff=client(),anonymous=client();
await anonymous.call();
await anonymous.call({action:'cart',store:'meijer'},401);
await owner.call({action:'signup',name:'Flow Test Owner',email:`owner-${nonce}@gather.test`,password:'TestPass123!'});
await guest.call({action:'signup',name:'Flow Test Guest',email:`guest-${nonce}@gather.test`,password:'TestPass123!'});
const escalation=await guest.call({action:'profile',name:'Flow Test Guest',phone:'',address:'',payment:'test-visa',role:'employee',store:'meijer'});assert.equal(escalation.user.role,'customer');
const c=await owner.call({action:'cart',store:'meijer'}),cart=c.cartId;
await guest.call({action:'item',cart,product:'banana',delta:1},403);
await owner.call({action:'item',cart,product:'croissant',delta:1},409);
await owner.call({action:'item',cart,product:'banana',delta:1});
const share=await owner.call({action:'share',cart});
await guest.call({action:'join',share:share.share});
await guest.call({action:'item',cart,product:'milk',delta:1});
const saved=await owner.call();assert.equal(saved.carts.find(c=>c.id===cart).items.length,2);
assert(!('password' in saved.user));
const pickup=new Date(Date.now()+86400000);pickup.setUTCHours(19,0,0,0);
const checkout={action:'checkout',cart,payment:'test-visa',person:'Flow Test Pickup',pickup:pickup.toISOString()};
await guest.call(checkout,403);
await owner.call({...checkout,pickup:new Date(Date.now()-1000).toISOString()},400);
const placed=await owner.call(checkout),id=placed.orderId,order=placed.orders.find(o=>o.id===id);
assert.equal(order.subtotal,568);assert.equal(order.fee,299);assert.equal(order.tax,61);assert.equal(order.status,'confirmed');assert(id.startsWith('MEI-'));
await owner.call(checkout,409);
await guest.call({action:'item',cart,product:'milk',delta:1},409);
await guest.call({action:'review',order:id,rating:5,comment:'Not my order'},403);
await owner.call({action:'status',order:id,status:'ready'},403);
await owner.call({action:'stock',product:'milk',available:100},403);
await owner.call({action:'review',order:id,rating:6,comment:'Invalid rating'},400);
await owner.call({action:'review',order:id,rating:5,comment:'Easy pickup. Everything was ready!'});
await owner.call({action:'review',order:id,rating:4,comment:'Duplicate review'},409);
const review=(await anonymous.call()).reviews.find(r=>r.order_id===id);assert.equal(review.store,'meijer');assert.equal(review.owner,order.owner);
await staff.call({action:'login',email:'staff@gather.test',password:'Gather123!'});
await staff.call({action:'status',order:id,status:'ready'},400);
for(const status of ['preparing','ready','collected'])await staff.call({action:'status',order:id,status});
assert.equal((await owner.call()).orders.find(o=>o.id===id).status,'collected');
const walmart=await owner.call({action:'cart',store:'walmart'});
await owner.call({action:'item',cart:walmart.cartId,product:'coffee',delta:1});
const worder=await owner.call({...checkout,cart:walmart.cartId});
await staff.call({action:'status',order:worder.orderId,status:'preparing'},403);
const inventoryCart=await owner.call({action:'cart',store:'meijer'});
await owner.call({action:'item',cart:inventoryCart.cartId,product:'pasta',delta:1});
await owner.call({action:'item',cart:inventoryCart.cartId,product:'pasta',delta:1});
const oldStock=(await staff.call()).stock.find(s=>s.store==='meijer'&&s.product==='pasta')?.available??24;
try {
 await staff.call({action:'stock',product:'pasta',available:0});
 const reduced=await owner.call({action:'item',cart:inventoryCart.cartId,product:'pasta',delta:-1});
 assert.equal(reduced.carts.find(c=>c.id===inventoryCart.cartId).items.find(i=>i.product==='pasta').quantity,1);
 await owner.call({action:'item',cart:inventoryCart.cartId,product:'pasta',delta:-1});
} finally { await staff.call({action:'stock',product:'pasta',available:oldStock}); }
await owner.call({action:'profile',name:'Flow Test Owner',phone:'555-0100',address:'Indianapolis, IN',payment:'test-mastercard'});
assert.equal((await owner.call()).user.payment,'test-mastercard');
await owner.call({action:'logout'});assert.equal((await owner.call()).user,null);
await owner.call({action:'cart',store:'meijer'},401);
await owner.call({action:'login',email:`owner-${nonce}@gather.test`,password:'WrongPassword'},401);
const restored=await owner.call({action:'login',email:`owner-${nonce}@gather.test`,password:'TestPass123!'});
assert.equal(restored.orders.length,2);
const badOrigin=await fetch(origin+'/api/gather',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://untrusted.example'},body:JSON.stringify({action:'login',email:'alex@gather.test',password:'Gather123!'})});assert.equal(badOrigin.status,403);
console.log('PASS: accounts, persistence, shared cart permissions, unavailable products, totals, pickup validation, verified reviews, staff store restrictions, status transitions, logout, and request origin checks.');
console.log(`Inspectable test order: ${id}`);
